# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de996a3bb233f6b48006ce2633551f6de90530b6b33aba481eebec17a53cbdd9ad9b984e49dc650b13306b413ea555c8199747c20d41cd8d8e44244fec04ff9f

test:
  secret_key_base: f94a83d80fa5732c0842ea55d9502597a5fe9b6dab3f884e2f753e06a7040e188bec3f564c1e1d816b21546220e368ca973189d100f35102901d778fc3075f49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
